server:
  port: 9000
spring:
  application:
    name: zuul-gateway
eureka:
  instance:
     hostname: localhost
  client:
     serviceUrl:
        defaultZone: http://localhost:9090/
zuul:
  routes:
    ServiceB:
       path: /demo/**
